name: ${pluginName}
main: com.aleksey.civvehicles.CivVehicles
version: ${version}
authors: [Aleksey-Terzi, Aidan]
description: ${description}
api-version: ${api_version}
commands:
    boat:
        description: Opens boat inventory.